### ISSUE TITLE
Can't download ckpt files correctly from LBC

### ISSUE THREAD

**Issue by Sumail2020** [scope-lab-vu/ANTI-CARLA#1]
Hello, Shreyasramakrishna90. Your work is great.
I encounter a problem while running the run_evaluation.sh. I think the reason is that I didn't download the LBC model (ckpt file)correctly, could you help me with that?  (P1 is the source from LBC, P2 is my problem, P3 is my folder)
![123](https://user-images.githubusercontent.com/71431119/204843691-95a46be3-9fdf-41c6-a5be-ded6c088fd69.png)
![ckpt](https://user-images.githubusercontent.com/71431119/204843709-8388d773-f6d1-45c0-a608-1c4c9a212b21.png)
![lbc](https://user-images.githubusercontent.com/71431119/204843725-4ac5f2b2-f15e-4b6e-ac53-3ec790596906.png)

**Comment by Sumail2020** [comment]
I have found the pretrained model from  LBC and figured it out my problem. Now it's running correctly
![2022-12-01 10-52-12屏幕截图](https://user-images.githubusercontent.com/71431119/204954967-2a5e6d74-e239-4732-8bea-fe16d93b42d8.png)

**Comment by Yzs-yzs** [comment]
Hello, Shreyasramakrishna90. Your work is great. But I found the GBO  sampling is not ok,Can you help me ?

**Comment by LifeIsBinary** [comment]
> I have found the pretrained model from LBC and figured it out my problem. Now it's running correctly ![2022-12-01 10-52-12屏幕截图](https://user-images.githubusercontent.com/71431119/204954967-2a5e6d74-e239-4732-8bea-fe16d93b42d8.png)

this link is not available now. Do you hold the model weights file of LBC in your computer?
