### ISSUE TITLE
The GBO

### ISSUE THREAD

**Issue by Yzs-yzs** [scope-lab-vu/ANTI-CARLA#2]
Hello, Shreyasramakrishna90. Your work is great. But I found the GBO sampling is not ok,Can you help me ?

**Comment by Shreyasramakrishna90** [comment]
Hi, can you provide me with your email address, so I can help you with your questions?

**Comment by Yzs-yzs** [comment]
> Hello, Shreyasramakrishna90. Your work is great. But I found the GBO sampling is not ok,Can you help me ?



> Hi, can you provide me with your email address, so I can help you with your questions？

Thank you very much. My email is 821419302@qq.com

**Comment by Yzs-yzs** [comment]
Thank you ! Your work is great
